### ISSUE TITLE
OverflowException: Value was either too large or too small for an unsigned byte

### ISSUE THREAD

**Issue by N3evin** [MrKev312/AmiiboGameListGenerator#1] opened 2021-07-10 12:20 UTC
Getting error on
```
Unhandled exception. System.InvalidOperationException: There is an error in XML document (39575, 3).
 ---> System.OverflowException: Value was either too large or too small for an unsigned byte.
   at System.Number.ThrowOverflowException(TypeCode type)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderSwitchreleases.Read2_SwitchreleasesRelease(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderSwitchreleases.Read3_Switchreleases(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderSwitchreleases.Read4_releases()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(Stream stream)
   at AmiiboGameList.Program.Main() in C:\Users\Martijn\Documents\GitHub\AmiiboGameListGenerator\AmiiboGameList\Program.cs:line 53
   ```

**Comment by MrKev312** [comment] 2021-07-11 11:51
Fixed in the latest release! Was caused by storing an image size of 4096 in a byte

**Closed by MrKev312** 2021-07-11 11:51 UTC
